### ISSUE TITLE
Junk characters before user@host on terminal

### ISSUE THREAD

**Issue by Hulth** [nightsense/nightshell#1]
After adding:
[ -n "$PS1" ] && sh ~/.nightshell/office-dark
to my .bashrc and exiting my editor my terminal looks like this:

\e]12;#949488\e]12;#949488user@host:~$

Using terminator on Ubuntu

**Comment by nightsense** [comment]
Thanks @Hulth, I've removed a troublesome line and that should be fixed now.

**Comment by Hulth** [comment]
Looks awesome now, thanks :)
