### ISSUE TITLE
[feature request] add back support for base16 script loader

### ISSUE THREAD

**Issue by metalelf0** [nightsense/nightshell#2]
Hi, first of all thanks for your themes - they are really good!

I'm already using the original base16 theme collection for my terminal, and considering your work is a derivative of Chris Kempson's work, it would be nice if you provided a way to merge the two collections.

It's as easy as typing, from your project's dir:

```
for file in *-light; do cp $file ~/.config/base16-shell/scripts/base16-nightshell-$file; done
for file in *-dark; do cp $file ~/.config/base16-shell/scripts/base16-nightshell-$file; done
```

So the user can toggle your themes with, e.g., `base16_nightshell-office-dark`.

Also, a link back to the original chriskempson/base16-shell repository could be appreciated. You might consider adding your project to [the list of scheme repositories](https://github.com/chriskempson/base16#scheme-repositories), but this is of course entirely up to you.

Thanks again!

**Comment by nightsense** [comment]
Sounds good, I added a section to the readme. Glad you like the themes! :frog:
