### ISSUE TITLE
stellarized?

### ISSUE THREAD

**Issue by ahmedelgabri** [nightsense/nightshell#3]
First amazing work in general, I really like what you are doing with colorschemes in general 👍 

Any plans to add https://github.com/nightsense/stellarized too to this project?

**Comment by nightsense** [comment]
Thanks! :smile: 

I won't be updating nightshell anymore, but before too long, I'm going to be rebuilding all my colorschemes using [Colortemplate](https://github.com/lifepillar/vim-colortemplate), which produces themes that work nicely in the terminal without the mess of shell scripts. As for theming the terminal itself, I might create terminal-specific themes depending on interest.

**Comment by ahmedelgabri** [comment]
Looking forward to what you are doing next then! 😊
